steps:
  # Build the Docker image using the Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/perala:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/perala:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    timeout: '1200s'
    
  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/perala:$COMMIT_SHA'
      
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'perala'
      - '--image'
      - 'gcr.io/$PROJECT_ID/perala:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      
# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/perala:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/perala:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  timeout: '1800s'
