steps:
  # Build the Docker image using the Dockerfile with Firebase config
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}'
      - '--build-arg'
      - 'VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/perala:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/perala:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    timeout: '1200s'
    
  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/perala:$COMMIT_SHA'
      
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'perala'
      - '--image'
      - 'gcr.io/$PROJECT_ID/perala:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'DATABASE_URL=sqlite.db,NODE_ENV=production,FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID},FIREBASE_CLIENT_EMAIL=${_FIREBASE_CLIENT_EMAIL},FIREBASE_PRIVATE_KEY=${_FIREBASE_PRIVATE_KEY},GEMINI_API_KEY=${_GEMINI_API_KEY},FYERS_APP_ID=${_FYERS_APP_ID},FYERS_SECRET_KEY=${_FYERS_SECRET_KEY},FYERS_ACCESS_TOKEN=${_FYERS_ACCESS_TOKEN}'
      
# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/perala:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/perala:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  timeout: '1800s'

# Substitution variables for Firebase config
# These values are embedded into the client bundle during build
substitutions:
  _VITE_FIREBASE_API_KEY: 'AIzaSyAg-jCM5IzgosNkdRJ2xQRZfFzl0C7LHZk'
  _VITE_FIREBASE_AUTH_DOMAIN: 'fast-planet-470408-f1.firebaseapp.com'
  _VITE_FIREBASE_PROJECT_ID: 'fast-planet-470408-f1'
  _VITE_FIREBASE_STORAGE_BUCKET: 'fast-planet-470408-f1.firebasestorage.app'
  _VITE_FIREBASE_MESSAGING_SENDER_ID: '808950990883'
  _VITE_FIREBASE_APP_ID: '1:808950990883:web:1252e6131d1f1c21688996'
